title: 4k4m1m3 | blog
description: "Blog personal de 4k4m1m3"
author:
  name: "4k4m1m3"
  email: "4k4m1m3@gmail.com"
  url: "https://4k4m1m3.github.io/"

baseurl: /
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true

plugins:
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-news-sitemap
  - jekyll-admin
  - jekyll-youtube
  - jekyll-email-protect
  
owner: "4k4m1m3"
year: "2024"
